"""Focused migration tests; all destinations and HOME are temporary.

Requires Git history containing PINNED, including its generated artifacts and
adapters. CI must checkout with fetch-depth: 0 (or fetch that commit explicitly).
Missing historical evidence fails the suite; never silently skip these checks or
substitute current generated bytes for the pinned baseline.
"""
import copy
import contextlib
import hashlib
import io
import json
import os
import re
from pathlib import Path
import subprocess
import tempfile
import unittest
from unittest.mock import patch

import retired_agents as migration
import test_install

ROOT = Path(__file__).resolve().parent.parent
PINNED = "d206ae811b14c44699c7040bdb59742eac1f122d"


class MigrationTests(unittest.TestCase):
    def setUp(self):
        output = contextlib.redirect_stdout(io.StringIO())
        output.__enter__()
        self.addCleanup(output.__exit__, None, None, None)
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        self.home = Path(self.temp.name).resolve()
        self.env = patch.dict(os.environ, {"HOME": str(self.home), "USERPROFILE": str(self.home)})
        self.env.start()
        self.addCleanup(self.env.stop)
        self.dest = self.home / ".claude/agents"
        self.dest.mkdir(parents=True)
        self.catalog = migration.load_catalog()
        self.entry = next(e for e in self.catalog if e["platform"] == "claude" and e["id"] == "architecture")
        self.path = self.dest / self.entry["filename"]
        self.bytes = subprocess.check_output(["git", "show", f"{PINNED}:generated/claude/agents/architecture.md"], cwd=ROOT)
        self.path.write_bytes(self.bytes)
        self.backup = self.home / "kit-retired-backups"

    def run_migration(self, **kwargs):
        return migration.migrate("claude", [self.dest], self.backup, **kwargs)

    def test_catalog_pinned_git_evidence(self):
        data = json.loads((ROOT / "tools/retired_agents.json").read_text())
        self.assertEqual(data["baseline_commit"], PINNED)
        self.assertEqual(len(self.catalog), 12)
        for entry in self.catalog:
            adapter = subprocess.check_output(["git", "show", f'{PINNED}:adapters/{entry["platform"]}/agents/{entry["id"]}.json'], cwd=ROOT)
            self.assertEqual(hashlib.sha256(adapter).hexdigest(), entry["adapter_sha256"])
            self.assertEqual(json.loads(adapter)["filename"], entry["filename"])
            artifact = subprocess.check_output(["git", "show", f'{PINNED}:generated/{entry["platform"]}/agents/{entry["filename"]}'], cwd=ROOT)
            self.assertEqual(hashlib.sha256(artifact).hexdigest(), entry["sha256"])

    def test_catalog_rejects_invalid_entries(self):
        data = json.loads((ROOT / "tools/retired_agents.json").read_text())
        for key, value in (("filename", "../architecture.md"), ("platform", "unknown"), ("id", "sdd"), ("sha256", "bad")):
            invalid = copy.deepcopy(data)
            invalid["entries"][0][key] = value
            with self.assertRaises(ValueError):
                migration.validate_catalog(invalid)
        invalid = copy.deepcopy(data)
        invalid["entries"].pop()
        with self.assertRaises(ValueError):
            migration.validate_catalog(invalid)

    def test_known_backup_restore_and_idempotence(self):
        self.assertEqual(self.run_migration(), 0)
        self.assertFalse(self.path.exists())
        copies = list(self.backup.rglob("*.md"))
        self.assertEqual(len(copies), 1)
        self.assertEqual(copies[0].read_bytes(), self.bytes)
        self.assertEqual(self.run_migration(), 0)
        self.assertEqual(list(self.backup.rglob("*.md")), copies)
        migration.restore(copies[0], self.path, self.entry["sha256"])
        with self.assertRaises(FileExistsError):
            migration.restore(copies[0], self.path, self.entry["sha256"])

    def test_uncertain_requires_exact_path_and_matching_hash(self):
        self.path.write_bytes(b"custom")
        sha = hashlib.sha256(b"custom").hexdigest()
        self.assertEqual(self.run_migration(), 1)
        self.assertEqual(self.run_migration(dry_run=True), 1)
        self.assertEqual(self.run_migration(approvals={str(self.path): "0" * 64}), 1)
        self.assertEqual(self.path.read_bytes(), b"custom")
        self.assertEqual(self.run_migration(approvals={str(self.path): sha}), 0)
        self.assertEqual(next(self.backup.rglob("*.md")).read_bytes(), b"custom")

    def test_dry_run_zero_writes(self):
        before = [(p, p.stat().st_mtime_ns) for p in self.home.rglob("*")]
        self.assertEqual(self.run_migration(dry_run=True), 0)
        self.assertEqual(before, [(p, p.stat().st_mtime_ns) for p in self.home.rglob("*")])

    def test_backup_outside_all_host_ancestors(self):
        for name in (".claude", ".agents", ".github", ".kiro", ".pi", ".gemini", ".copilot", ".opencode"):
            self.assertEqual(migration.migrate("claude", [self.dest], self.home / name / "backups"), 1)
        self.assertEqual(migration.migrate("claude", [self.dest], self.home / ".config/opencode/backups"), 1)
        self.assertTrue(self.path.exists())

    def test_symlink_and_parent_symlink_blocked(self):
        self.path.unlink()
        other = self.home / "other.md"
        other.write_bytes(self.bytes)
        self.path.symlink_to(other)
        self.assertEqual(self.run_migration(), 1)
        self.assertTrue(other.exists())
        self.path.unlink()
        self.dest.rmdir()
        self.dest.symlink_to(self.home)
        self.assertEqual(self.run_migration(), 1)

    def test_nonregular_candidate_rejected_before_open(self):
        self.path.unlink()
        self.path.mkdir()
        with patch.object(migration.os, "open", side_effect=OSError("must not open directory")) as opened:
            with self.assertRaises(OSError):
                migration.read_regular(self.path)
            opened.assert_not_called()

    def test_copy_failure_and_changed_original_preserved(self):
        with patch.object(migration, "write_backup", side_effect=OSError("copy failed")):
            self.assertEqual(self.run_migration(), 1)
        self.assertEqual(self.path.read_bytes(), self.bytes)
        original = migration.write_backup
        def changed(*args):
            result = original(*args)
            self.path.write_bytes(b"changed during backup")
            return result
        with patch.object(migration, "write_backup", side_effect=changed):
            self.assertEqual(self.run_migration(), 1)
        self.assertEqual(self.path.read_bytes(), b"changed during backup")

    def test_bad_backup_and_unique_retry_preserve_evidence(self):
        original = migration.write_backup
        def corrupt(*args):
            target = original(*args)
            target.write_bytes(b"corrupt")
            return target
        with patch.object(migration, "write_backup", side_effect=corrupt):
            self.assertEqual(self.run_migration(), 1)
        self.assertEqual(self.path.read_bytes(), self.bytes)
        self.assertEqual(self.run_migration(), 0)
        copies = list(self.backup.rglob("*.md"))
        self.assertEqual(len(copies), 2)
        self.assertEqual({p.read_bytes() for p in copies}, {b"corrupt", self.bytes})

    def test_backup_parent_symlink_and_file_blocked(self):
        self.backup.symlink_to(self.home / ".claude")
        self.assertEqual(self.run_migration(), 1)
        self.backup.unlink()
        self.backup.write_bytes(b"not a directory")
        self.assertEqual(self.run_migration(), 1)
        self.assertEqual(self.path.read_bytes(), self.bytes)

    def test_backup_inside_other_configured_host_blocked(self):
        configured = self.home / "custom-other-host"
        with patch.dict(os.environ, {"PI_CODING_AGENT_DIR": str(configured)}):
            self.assertEqual(migration.migrate("claude", [self.dest], configured / "backups"), 1)
        self.assertTrue(self.path.exists())

    def test_backup_custom_active_destinations(self):
        global_dest = self.home / "custom-global/agents"
        local_dest = self.home / "project/custom-local/prompts"
        for dest in (global_dest, local_dest):
            dest.mkdir(parents=True)
            (dest / "architecture.md").write_bytes(self.bytes)
        destinations = [global_dest, local_dest]
        for dest in destinations:
            for backup in (dest / "backups", dest.parent / "backups"):
                self.assertEqual(migration.migrate("claude", destinations, backup), 1)
                self.assertFalse(backup.exists())
        self.assertEqual(migration.migrate("claude", destinations, self.backup), 0)
        copies = list(self.backup.rglob("*.md"))
        self.assertEqual(len(copies), 2)
        self.assertTrue(all(p.read_bytes() == self.bytes for p in copies))
        self.assertTrue(all(not (dest / "architecture.md").exists() for dest in destinations))

    def test_build_repo_includes_migration_tooling(self):
        with tempfile.TemporaryDirectory() as temporary:
            repo = test_install.build_repo(Path(temporary).resolve())
            for name in ("retired_agents.json", "retired_agents.py", "install_preflight.py", "test_retired_agents.py"):
                self.assertEqual((repo / "tools" / name).read_bytes(), (ROOT / "tools" / name).read_bytes())

    def test_wrappers_reject_unsafe_copy_targets_before_writes(self):
        for platform in test_install.PLATFORMS:
            for defect in ("skills-root-link", "skill-link", "nested-reference-link", "reference-file-link", "current-agent-link", "backup-file", "backup-parent-file"):
                with self.subTest(platform=platform, defect=defect), tempfile.TemporaryDirectory() as temporary:
                    base = Path(temporary).resolve()
                    repo = test_install.build_repo(base)
                    home = base / "home"
                    home.mkdir()
                    skills, agents = test_install.installed_paths(home, platform)
                    agents.mkdir(parents=True)
                    entry = next(e for e in self.catalog if e["platform"] == platform and e["id"] == "architecture")
                    candidate = agents / entry["filename"]
                    candidate.write_bytes(b"original retired custom")
                    outside = base / "outside"
                    outside.mkdir()
                    sentinel = outside / "sentinel.md"
                    sentinel.write_bytes(b"outside must not change")
                    if defect == "skills-root-link":
                        skills.symlink_to(outside, target_is_directory=True)
                    elif defect == "skill-link":
                        skills.mkdir()
                        (skills / "architecture").symlink_to(outside, target_is_directory=True)
                    elif defect in {"nested-reference-link", "reference-file-link"}:
                        skill = skills / "architecture"
                        skill.mkdir(parents=True)
                        if defect == "nested-reference-link":
                            (skill / "references").symlink_to(outside, target_is_directory=True)
                        else:
                            (skill / "references").mkdir()
                            (skill / "references/templates.md").symlink_to(sentinel)
                    elif defect == "current-agent-link":
                        name = test_install.agent_filenames(platform, ["documentation-orchestrator"])[0]
                        (agents / name).symlink_to(sentinel)
                    else:
                        backup = home / ".ai-agents-kit-retired-backups"
                        backup.write_bytes(b"not a directory")
                        if defect == "backup-parent-file":
                            # Exercise an existing non-directory parent as well.
                            backup.unlink()
                            backup.mkdir()
                            (backup / "blocked").write_bytes(b"not a directory")
                            script = repo / f"scripts/install/{platform}.sh"
                            script.write_text(script.read_text().replace('$HOME/.ai-agents-kit-retired-backups', '$HOME/.ai-agents-kit-retired-backups/blocked/child'))
                    before_home = [(str(p), p.lstat().st_mtime_ns) for p in home.rglob("*")]
                    before_outside = [(str(p), hashlib.sha256(p.read_bytes()).hexdigest()) for p in outside.rglob("*") if p.is_file()]
                    result = test_install.run_installer(repo, home, platform, "--migrate-retired-agents", "--force")
                    self.assertEqual([(str(p), hashlib.sha256(p.read_bytes()).hexdigest()) for p in outside.rglob("*") if p.is_file()], before_outside, result.stdout + result.stderr)
                    self.assertEqual([(str(p), p.lstat().st_mtime_ns) for p in home.rglob("*")], before_home, result.stdout + result.stderr)
                    self.assertEqual(result.returncode, 1, result.stdout + result.stderr)
                    self.assertEqual(candidate.read_bytes(), b"original retired custom")

    def test_backup_structure_invalid_in_dry_run(self):
        self.backup.write_bytes(b"file")
        for backup in (self.backup, self.backup / "child"):
            with self.subTest(backup=backup):
                with self.assertRaises(OSError):
                    migration.validate_backup(backup, [self.dest])
                self.assertEqual(migration.migrate("claude", [self.dest], backup, dry_run=True), 1)
        self.assertEqual(self.path.read_bytes(), self.bytes)

    def test_approval_hint_posix_roundtrip(self):
        dest = self.home / "proyecto é ' \" $HOME \\ literal/agents"
        dest.mkdir(parents=True)
        candidate = dest / "architecture.md"
        candidate.write_bytes(b"unknown")
        sha = hashlib.sha256(b"unknown").hexdigest()
        output = io.StringIO()
        with contextlib.redirect_stdout(output):
            self.assertEqual(migration.migrate("claude", [dest], self.backup, dry_run=True), 1)
        hint = next(line.removeprefix("pendiente: ") for line in output.getvalue().splitlines() if line.startswith("pendiente: "))
        # Parse with a real shell, without executing the migration or writing files.
        result = subprocess.run(["bash", "-c", "set -- " + hint + "; python3 -c 'import json,sys; print(json.dumps(sys.argv[1:]))' \"$@\""], capture_output=True, text=True)
        self.assertEqual(result.returncode, 0, result.stderr)
        args = json.loads(result.stdout)
        self.assertEqual(args[args.index("--approve-retired-file") + 1], str(candidate))
        self.assertEqual(args[args.index("--approve-retired-sha256") + 1], sha)
        self.assertIn("--migrate-retired-agents", args)

    def test_approval_hint_powershell_exact_literals(self):
        candidate = "C:\\Usuarios\\José O'Neil\\proyecto \"literal\"\\.claude\\agents\\architecture.md"
        sha = "a" * 64
        hint = migration.approval_hint(candidate, sha, "claude", ["C:\\kit\\agents"], "C:\\backup", shell="powershell")
        self.assertTrue(hint.startswith("& 'python' "))
        self.assertIn("'C:\\Usuarios\\José O''Neil\\proyecto \"literal\"\\.claude\\agents\\architecture.md'", hint)
        # PowerShell single-quoted literals escape only apostrophes by doubling.
        literals = re.findall(r"'((?:[^']|'')*)'", hint[2:])
        args = [value.replace("''", "'") for value in literals]
        self.assertEqual(args[args.index("--approve-retired-file") + 1], candidate)
        self.assertEqual(args[args.index("--approve-retired-sha256") + 1], sha)
        self.assertEqual("& " + " ".join("'" + value.replace("'", "''") + "'" for value in args), hint)

    def test_unlink_failure_preserves_original_and_backup(self):
        with patch.object(migration, "remove_verified", side_effect=OSError("unlink failed")):
            self.assertEqual(self.run_migration(), 1)
        self.assertEqual(self.path.read_bytes(), self.bytes)
        self.assertEqual(next(self.backup.rglob("*.md")).read_bytes(), self.bytes)

    def test_post_unlink_failure_recovers_without_overwrite(self):
        original = migration.remove_verified
        def failed_after_unlink(*args):
            original(*args)
            raise OSError("post-unlink failure")
        with patch.object(migration, "remove_verified", side_effect=failed_after_unlink):
            self.assertEqual(self.run_migration(), 1)
        self.assertEqual(self.path.read_bytes(), self.bytes)
        def recreated(*args):
            original(*args)
            self.path.write_bytes(b"new user work")
            raise OSError("post-unlink failure")
        with patch.object(migration, "remove_verified", side_effect=recreated):
            self.assertEqual(self.run_migration(), 1)
        self.assertEqual(self.path.read_bytes(), b"new user work")

    def test_restore_rejects_wrong_hash_and_symlink(self):
        self.assertEqual(self.run_migration(), 0)
        backup = next(self.backup.rglob("*.md"))
        with self.assertRaises(OSError):
            migration.restore(backup, self.path, "0" * 64)
        self.assertFalse(self.path.exists())
        self.path.symlink_to(self.home / "absent")
        with self.assertRaises(OSError):
            migration.restore(backup, self.path, self.entry["sha256"])

    def test_approval_validation_exact_repeated_paths(self):
        other = self.dest / "project-navigator.md"
        paths = [str(self.path), str(other)]
        hashes = [self.entry["sha256"], "0" * 64]
        self.assertEqual(migration.approvals_from_args(paths, hashes, [self.dest], "claude"), dict(zip(paths, hashes)))
        for invalid in ([str(self.dest / "*.md")], [str(self.home / "other.md")], [str(self.path) + "/../architecture.md"], ["architecture.md"]):
            with self.assertRaises(ValueError):
                migration.approvals_from_args(invalid, hashes[:1], [self.dest], "claude")
        with self.assertRaises(ValueError):
            migration.approvals_from_args(paths, hashes[:1], [self.dest], "claude")

    def test_real_wrappers_opt_in_force_dry_run_and_invalid_flags(self):
        for platform in test_install.PLATFORMS:
            with self.subTest(platform=platform), tempfile.TemporaryDirectory() as temporary:
                base = Path(temporary).resolve()
                repo = test_install.build_repo(base)
                manifest_path = repo / "canonical/manifest.json"
                manifest = json.loads(manifest_path.read_text())
                manifest["agents"] = [a for a in manifest["agents"] if a not in migration.IDS]
                # Keep this fixture focused on one stable skill, independently of
                # the main renderer's current documentation resources.
                manifest["skills"] = ["git-commit"]
                manifest_path.write_text(json.dumps(manifest))
                for entry in self.catalog:
                    if entry["platform"] == platform:
                        (repo / "generated" / platform / "agents" / entry["filename"]).unlink(missing_ok=True)
                home = base / "home"
                home.mkdir()
                _, dest = test_install.installed_paths(home, platform)
                dest.mkdir(parents=True)
                entry = next(e for e in self.catalog if e["platform"] == platform and e["id"] == "architecture")
                path = dest / entry["filename"]
                old = subprocess.check_output(["git", "show", f'{PINNED}:generated/{platform}/agents/{entry["filename"]}'], cwd=ROOT)
                path.write_bytes(old)
                result = test_install.run_installer(repo, home, platform, "--approve-retired-file", str(path))
                self.assertEqual(result.returncode, 2, result.stdout + result.stderr)
                self.assertEqual(list(home.rglob("*.md")), [path])
                result = test_install.run_installer(repo, home, platform, "--force")
                self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
                self.assertEqual(path.read_bytes(), old)
                self.assertIn("migración", result.stdout)
                before = [(p, p.stat().st_mtime_ns) for p in home.rglob("*")]
                result = test_install.run_installer(repo, home, platform, "--migrate-retired-agents", "--dry-run")
                self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
                self.assertEqual(before, [(p, p.stat().st_mtime_ns) for p in home.rglob("*")])
                result = test_install.run_installer(repo, home, platform, "--migrate-retired-agents", "--force")
                self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
                self.assertFalse(path.exists())
                copies = list((home / ".ai-agents-kit-retired-backups").rglob("*.md"))
                self.assertEqual(len(copies), 1)
                self.assertEqual(copies[0].read_bytes(), old)
                # --force never approves unknown bytes; approvals are repeatable.
                path.write_bytes(b"custom architecture")
                other_entry = next(e for e in self.catalog if e["platform"] == platform and e["id"] == "project-navigator")
                other = dest / other_entry["filename"]
                other.write_bytes(b"custom navigator")
                extra = dest / "personal.md"
                extra.write_bytes(b"personal agent")
                result = test_install.run_installer(repo, home, platform, "--migrate-retired-agents", "--force")
                self.assertEqual(result.returncode, 1, result.stdout + result.stderr)
                self.assertEqual(path.read_bytes(), b"custom architecture")
                self.assertEqual(other.read_bytes(), b"custom navigator")
                flags = ["--migrate-retired-agents", "--force"]
                for candidate in (path, other):
                    flags.extend(["--approve-retired-file", str(candidate), "--approve-retired-sha256", hashlib.sha256(candidate.read_bytes()).hexdigest()])
                result = test_install.run_installer(repo, home, platform, *flags)
                self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
                self.assertFalse(path.exists())
                self.assertFalse(other.exists())
                self.assertEqual(extra.read_bytes(), b"personal agent")
                copies = list((home / ".ai-agents-kit-retired-backups").rglob("*.md"))
                self.assertEqual(len(copies), 3)
                result = test_install.run_installer(repo, home, platform, "--migrate-retired-agents", "--force")
                self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
                self.assertEqual(list((home / ".ai-agents-kit-retired-backups").rglob("*.md")), copies)

    def test_explicit_local_destination_real_wrapper(self):
        with tempfile.TemporaryDirectory() as temporary:
            base = Path(temporary).resolve()
            repo = test_install.build_repo(base)
            manifest_path = repo / "canonical/manifest.json"
            manifest = json.loads(manifest_path.read_text())
            manifest["agents"] = [a for a in manifest["agents"] if a not in migration.IDS]
            manifest["skills"] = ["git-commit"]
            manifest_path.write_text(json.dumps(manifest))
            for entry in self.catalog:
                if entry["platform"] == "claude":
                    (repo / "generated/claude/agents" / entry["filename"]).unlink(missing_ok=True)
            home = base / "home"
            home.mkdir()
            local = base / "project/.claude/agents"
            local.mkdir(parents=True)
            candidate = local / "architecture.md"
            candidate.write_bytes(self.bytes)
            result = test_install.run_installer(repo, home, "claude", "--migrate-retired-agents", "--force", "--additional-agents-dest", str(local))
            self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
            self.assertFalse(candidate.exists())
            self.assertEqual(next((home / ".ai-agents-kit-retired-backups").rglob("*.md")).read_bytes(), self.bytes)

    def test_powershell_policy_parity(self):
        for platform in test_install.PLATFORMS:
            content = (ROOT / f"scripts/install/{platform}.ps1").read_text()
            for flag in ("--migrate-retired-agents", "--validate-migration", "--approve-retired-file", "--approve-retired-sha256"):
                self.assertIn(flag, content)
            self.assertLess(content.index("Invoke-RetiredMigration -ValidateOnly"), content.index('if (-not (Invoke-Preflight'))

    def test_preflight_current_bytes_and_check_installed_read_only(self):
        with tempfile.TemporaryDirectory() as temporary:
            base = Path(temporary).resolve()
            repo = test_install.build_repo(base)
            manifest_path = repo / "canonical/manifest.json"
            manifest = json.loads(manifest_path.read_text())
            manifest["agents"] = ["documentation-orchestrator"]
            manifest["skills"] = ["git-commit"]
            manifest_path.write_text(json.dumps(manifest))
            for entry in self.catalog:
                if entry["platform"] == "claude":
                    (repo / "generated/claude/agents" / entry["filename"]).unlink(missing_ok=True)
            home = base / "home"
            home.mkdir()
            self.assertEqual(test_install.run_installer(repo, home, "claude", "--force").returncode, 0)
            skills, dest = test_install.installed_paths(home, "claude")
            path = dest / "architecture.md"
            path.write_bytes(self.bytes)
            active = dest / "documentation-orchestrator.md"
            active.write_bytes(b"broken install")
            env = {**os.environ, "HOME": str(home), "USERPROFILE": str(home), "PYTHONDONTWRITEBYTECODE": "1"}
            common = ["python3", "-B", str(repo / "tools/install_preflight.py"), "--platform", "claude", "--skills-dest", str(skills), "--agents-dest", str(dest)]
            before = [(p, p.stat().st_mtime_ns) for p in home.rglob("*")]
            result = subprocess.run([*common, "--check-installed"], capture_output=True, text=True, env=env)
            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertNotIn("Migración completada", result.stdout)
            self.assertEqual(before, [(p, p.stat().st_mtime_ns) for p in home.rglob("*")])
            result = subprocess.run([*common, "--migrate-retired-agents"], capture_output=True, text=True, env=env)
            self.assertEqual(result.returncode, 1, result.stdout + result.stderr)
            self.assertEqual(path.read_bytes(), self.bytes)
            self.assertFalse((home / ".ai-agents-kit-retired-backups").exists())


if __name__ == "__main__":
    unittest.main()
